### ISSUE TITLE
How to load string if it is not valid JSON?

### ISSUE THREAD

**Issue by anselanza** [fpirsch/vptree.js#2]
I have one application that builds my VP Tree, stringify's it and writes it to a file.

I have another application that needs to load in the VP Tree object from the file, but of course it is not valid JSON... How then do I parse the string as an object?

**Comment by fpirsch** [comment]
Hi @anselanza !
Why not just write `JSON.stringify(vptree.tree)` instead of `ptree.stringify()` in the first place ?

**Comment by anselanza** [comment]
Ah, I had no idea that the `vptree.tree` was accessible like that. Makes sense!
